---
- name: Add RCM APT Repository
  become: yes
  apt_repository:
    repo: ppa:martin-frost/thoughtbot-rcm

- name: Install RCM
  become: yes
  package:
    name: rcm

- name: Fetch dotfiles
  git:
    dest: ~/.dotfiles
    repo: git@github.com:e4r7hbug/dotfiles.git
    update: no

- name: Run RCM
  command: rcup -v -t python
