---
- name: Upgrade System
  become: yes
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 43200

- name: Install standard applications
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: no
  with_items:
    - atop
    - bash-completion
    - dnstop
    - git
    - htop
    - iftop
    - iotop
    - itop
    - procps
    - screen
    - silversearcher-ag
    - tmux
    - tree
    - xclip
    - vim

    # build tools
    - build-essential
    - clang
    - clang-format-3.7

    # development packages
    - zeal

- name: Create main user
  become: yes
  user:
    name: "{{ user }}"

- include:
    dotfiles.yml
