---
- hosts: all
  tasks:
  - name: Create main user
    become: yes
    user:
      name: ntangsurat
      groups:
        - docker
        - sudo

- hosts: all
  remote_user: ntangsurat
  vars:
    user: ntangsurat
  roles:
  - init
  - rcm
  - python
