---
- name: Get the dots!
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/e4r7hbug/dotfiles.git
    dest: "{{ dotfiles }}"

- name: Set up some needed directories
  become: yes
  become_user: "{{ user }}"
  file:
    path: "~{{ user }}/.config/pip/"
    state: directory

- name: Lace up the dots
  become: yes
  become_user: "{{ user }}"
  file:
    src: "{{ dotfiles }}/{{ item }}"
    dest: "~{{ user }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - .bash_aliases
    - .bash_ntangsurat
    - .bashrc
    - .config/pip/pip.conf
    - .gitconfig
    - .gittemplate
    - .profile
    - .pylintrc
    - .ssh
    - .tmux.conf
    - .vimrc

- name: Generate SSH key now that .ssh is in place
  become: yes
  become_user: "{{ user }}"
  user:
    name: "{{ user }}"
    generate_ssh_key: yes
