---
- name: Upgrade System
  become: yes
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 43200

- name: Install standard applications
  become: yes
  package:
    name: "{{ item }}"
    state: latest
    update_cache: no
  with_items:
    - atop
    - bash-completion
    - dnstop
    - git
    - htop
    - iftop
    - iotop
    - itop
    - most
    - procps
    - screen
    - silversearcher-ag
    - tmux
    - tree
    - vim
    - xclip

    # build tools
    - build-essential
    - clang
    - clang-format

    # development packages
    - zeal

- include:
    dotfiles.yml
